### ISSUE TITLE
Exception format incompatible with previous versions

### ISSUE THREAD

**Issue by evanj** [farcepest/MySQLdb1#1]
I'm not sure if this is a bug in MySQL-Python or in SQLAlchemy, so I'm reporting it in both places. I just did a pip install today for a clean build, and I got the following exception (along with the database trace) from SQLAlchemy. Downgrading to 1.2.3 makes the error go away. It seems similar to the following old thread, where MySQL-Python changed the exception format. I didn't investigate this further, but am happy to do any debugging you may need. Thanks!

New SQLAlchemy thread about this: 
https://groups.google.com/d/topic/sqlalchemy/POGzAtvzD4A/discussion

Old SQLAlchemy thread that may be related:
https://groups.google.com/d/topic/sqlalchemy/3DDRA-2oWWc/discussion

Exception and SQL log:

2012-09-26 13:41:48,217 INFO sqlalchemy.engine.base.Engine SELECT DATABASE()
[I 120926 13:41:48 log:107] SELECT DATABASE()
2012-09-26 13:41:48,218 INFO sqlalchemy.engine.base.Engine ()
[I 120926 13:41:48 log:107]()
2012-09-26 13:41:48,219 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'character_set%%'
[I 120926 13:41:48 log:107] SHOW VARIABLES LIKE 'character_set%%'
2012-09-26 13:41:48,219 INFO sqlalchemy.engine.base.Engine ()
[I 120926 13:41:48 log:107]()
2012-09-26 13:41:48,220 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'lower_case_table_names'
[I 120926 13:41:48 log:107] SHOW VARIABLES LIKE 'lower_case_table_names'
2012-09-26 13:41:48,220 INFO sqlalchemy.engine.base.Engine ()
[I 120926 13:41:48 log:107]()
2012-09-26 13:41:48,221 INFO sqlalchemy.engine.base.Engine SHOW COLLATION
[I 120926 13:41:48 log:107] SHOW COLLATION
2012-09-26 13:41:48,221 INFO sqlalchemy.engine.base.Engine ()
[I 120926 13:41:48 log:107]()
2012-09-26 13:41:48,224 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'sql_mode'
[I 120926 13:41:48 log:107] SHOW VARIABLES LIKE 'sql_mode'
2012-09-26 13:41:48,224 INFO sqlalchemy.engine.base.Engine ()
[I 120926 13:41:48 log:107]()
2012-09-26 13:41:48,226 INFO sqlalchemy.engine.base.Engine DESCRIBE "newaccounttoken"
[I 120926 13:41:48 log:107] DESCRIBE "newaccounttoken"
2012-09-26 13:41:48,226 INFO sqlalchemy.engine.base.Engine ()
[I 120926 13:41:48 log:107]()
2012-09-26 13:41:48,229 INFO sqlalchemy.engine.base.Engine ROLLBACK
[I 120926 13:41:48 log:107] ROLLBACK
Traceback (most recent call last):
  File "configuration/mysql/makedb.py", line 93, in <module>
    main()
  File "configuration/mysql/makedb.py", line 82, in main
    server.models.createDB()
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/server/models.py", line 534, in createDB
    Base.metadata.create_all(server.db.get_engine())
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2564, in create_all
    tables=tables)
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2303, in _run_visitor
    conn._run_visitor(visitorcallable, element, *_kwargs)
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1973, in _run_visitor
    *_kwargs).traverse_single(element)
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 106, in traverse_single
    return meth(obj, **kw)
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 54, in visit_metadata
    if self._can_create_table(t)]
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 32, in _can_create_table
    table.name, schema=table.schema)
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 1986, in has_table
    rs = connection.execute(st)
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1449, in execute
    params)
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1628, in _execute_text
    statement, parameters
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1698, in _execute_context
    context)
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1691, in _execute_context
    context)
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 331, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 181, in execute
    self.errorhandler(self, exc, value)
  File "/Users/ej/unnamed/build/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass(errorvalue)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) (1146, "Table 'lectorius.newaccounttoken' doesn't exist") 'DESCRIBE "newaccounttoken"' ()

**Comment by farcepest** [comment]
I inadvertently resurrected http://sourceforge.net/p/mysql-python/bugs/277/

I'll revert the change that did this

**Comment by farcepest** [comment]
Should be fixed in d1b43681cfe61adf994e9cb4cd495556eb712c6e

Congratulations on reporting issue #1
