### ISSUE TITLE
 No module named 'ConfigParser' while set up

### ISSUE THREAD

**Issue by dvska** [farcepest/MySQLdb1#14]
Latest Ubuntu x64, Python 2.7.3, pip 1.3.1:

``` python
$ sudo pip install MySQL-python==1.2.4

Downloading/unpacking MySQL-python==1.2.4
  Downloading MySQL-python-1.2.4.zip (113kB): 113kB downloaded
  Running setup.py egg_info for package MySQL-python
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build-root/MySQL-python/setup.py", line 14, in <module>
        from setup_posix import get_config
      File "./setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ImportError: No module named 'ConfigParser'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build-root/MySQL-python/setup.py", line 14, in <module>

    from setup_posix import get_config

  File "./setup_posix.py", line 2, in <module>

    from ConfigParser import SafeConfigParser

ImportError: No module named 'ConfigParser'
```

**Comment by s7v7nislands** [comment]
ConfigParser is in python2.7's stdlib. Are you sure you using python2.7 not python3? 

sudo pip --version will show which version of python you using.

**Comment by farcepest** [comment]
What s7v7nilands said
