### ISSUE TITLE
Issue installing the package on python 3.7.2

### ISSUE THREAD

**Issue by NFSpeedy** [farcepest/MySQLdb1#145]
```
root@here:~ # pip3.7 install MySQL-python
Collecting MySQL-python
Downloading https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip (108kB)
100% |████████████████████████████████| 112kB 862kB/s 
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-3cxb4zwo/MySQL-python/setup.py", line 13, in <module>
from setup_posix import get_config
File "/tmp/pip-install-3cxb4zwo/MySQL-python/setup_posix.py", line 2, in <module>
from ConfigParser import SafeConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-3cxb4zwo/MySQL-python/
```

**Comment by methane** [comment]
This project is not maintained for a long time.  Use mysqlclient instead.
