### ISSUE TITLE
GCC CCache Installation Error

### ISSUE THREAD

**Issue by Renegade605** [farcepest/MySQLdb1#37]
Hello,

I've been trying to install Python-MySQL to my linux-based server for quite a while, but I'm having considerable difficulty. When trying to "python setup.py build" OR "pip install python-mysql" the setup crashes. Here is the log:

```
    ~ # pip install mysql-python
    Downloading/unpacking mysql-python
    Downloading MySQL-python-1.2.4.zip (113kB): 113kB downloaded
    Running setup.py egg_info for package mysql-python
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.28.tar.gz
    Extracting in /tmp/tmpzbri8D
    Now working in /tmp/tmpzbri8D/distribute-0.6.28
    Building a Distribute egg in /tmp/pip_build_root/mysql-python
    /tmp/pip_build_root/mysql-python/distribute-0.6.28-py2.7.egg

    Installing collected packages: mysql-python
    Running setup.py install for mysql-python
    building '_mysql' extension
    /usr/local/i686-linux-gnu/bin/i686-linux-gnu-ccache-gcc -fno-strict-aliasing -I/usr/syno/include/ncurses/ -I. -I./Modules/expat/ -I/usr/local/i686-linux-gnu/include -DSYNO_X86 -O2 -I/usr/syno/include -g -DSYNO_PLATFORM=X64 -g -DSDK_VER_MIN_REQUIRED=400 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Dversion_info=(1,2,4,'final',1) -Dversion=1.2.4 -I/usr/local/include -I/usr/local/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o -g -DUNIV_LINUX -DUNIV_LINUX
    unable to execute /usr/local/i686-linux-gnu/bin/i686-linux-gnu-ccache-gcc: No such file or directory
    error: command '/usr/local/i686-linux-gnu/bin/i686-linux-gnu-ccache-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;file='/tmp/pip_build_root/mysql-python/setup.py';exec(compile(open(file).read().replace('\r\n', '\n'), file, 'exec'))" install --record /tmp/pip-kb3_p7-record/install-record.txt --single-version-externally-managed:
    running install

    running build

    running build_py

    creating build

    creating build/lib.linux-x86_64-2.7

    copying _mysql_exceptions.py -> build/lib.linux-x86_64-2.7

    creating build/lib.linux-x86_64-2.7/MySQLdb

    copying MySQLdb/init.py -> build/lib.linux-x86_64-2.7/MySQLdb

    copying MySQLdb/converters.py -> build/lib.linux-x86_64-2.7/MySQLdb

    copying MySQLdb/connections.py -> build/lib.linux-x86_64-2.7/MySQLdb

    copying MySQLdb/cursors.py -> build/lib.linux-x86_64-2.7/MySQLdb

    copying MySQLdb/release.py -> build/lib.linux-x86_64-2.7/MySQLdb

    copying MySQLdb/times.py -> build/lib.linux-x86_64-2.7/MySQLdb

    creating build/lib.linux-x86_64-2.7/MySQLdb/constants

    copying MySQLdb/constants/init.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

    copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

    copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

    copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

    copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

    copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

    copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

    running build_ext

    building '_mysql' extension

    creating build/temp.linux-x86_64-2.7

    /usr/local/i686-linux-gnu/bin/i686-linux-gnu-ccache-gcc -fno-strict-aliasing -I/usr/syno/include/ncurses/ -I. -I./Modules/expat/ -I/usr/local/i686-linux-gnu/include -DSYNO_X86 -O2 -I/usr/syno/include -g -DSYNO_PLATFORM=X64 -g -DSDK_VER_MIN_REQUIRED=400 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Dversion_info=(1,2,4,'final',1) -Dversion=1.2.4 -I/usr/local/include -I/usr/local/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o -g -DUNIV_LINUX -DUNIV_LINUX

    unable to execute /usr/local/i686-linux-gnu/bin/i686-linux-gnu-ccache-gcc: No such file or directory

    error: command '/usr/local/i686-linux-gnu/bin/i686-linux-gnu-ccache-gcc' failed with exit status 1

    Cleaning up...
    Command /usr/bin/python -c "import setuptools;file='/tmp/pip_build_root/mysql-python/setup.py';exec(compile(open(file).read().replace('\r\n', '\n'), file, 'exec'))" install --record /tmp/pip-kb3_p7-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip_build_root/mysql-python
    Storing complete log in /root/.pip/pip.log
```

I do have GCC installed on my server so I cannot figure out why the setup is looking for a GCC related file that does not exist. Any help would be greatly appreciated.

**Comment by Watzmann** [comment]
Have a look into your /root/.pip/pip.log as indicated in your last line.
I remember faintly, that I had problems. But installation using easy-install worked fine, then.

**Comment by Renegade605** [comment]
Thanks for the reply. Taking a look through that log and it doesn't reveal anything to me that is helpful; I posted it anyway in case I'm overlooking something.

I did try installing with easy_install but the process failed in the same manner.

```
 ------------------------------------------------------------
/usr/local/bin/pip run on Mon Oct 28 19:31:04 2013
Downloading/unpacking mysql-python

  Getting page https://pypi.python.org/simple/mysql-python/
  URLs to search for versions for mysql-python:
  * https://pypi.python.org/simple/mysql-python/
  Analyzing links from page https://pypi.python.org/simple/MySQL-python/
    Skipping link https://pypi.python.org/packages/2.4/M/MySQL-python/MySQL_python-1.2.2-py2.4-win32.egg#md5=6620279666cb40e26d89079b55e61a3f (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.5/M/MySQL-python/MySQL_python-1.2.2-py2.5-win32.egg#md5=596ec38e498e80ce73759f777b29c588 (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.5/M/MySQL-python/MySQL_python-1.2.3b1-py2.5-linux-i686.egg#md5=43ace300f3eda0fc418869b04a5139eb (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.5/M/MySQL-python/MySQL_python-1.2.3b2-py2.5-linux-i686.egg#md5=36f78115685d8ed96ab9199c36ef0ab0 (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.5/M/MySQL-python/MySQL_python-1.2.3c1-py2.5-linux-i686.egg#md5=1efcbed6f1f29acd50993f54109938d3 (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.6/M/MySQL-python/MySQL_python-1.2.3b1-py2.6-linux-i686.egg#md5=4a640ca00352a18e0a8211e935406100 (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.6/M/MySQL-python/MySQL_python-1.2.3b2-py2.6-linux-i686.egg#md5=08ba3e38b899a70a1a2bb3239107acae (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.6/M/MySQL-python/MySQL_python-1.2.3c1-py2.6-linux-i686.egg#md5=fd472a7c42ef80bd671272a25d6aadf8 (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/M/MySQL-python/MySQL-python-1.2.4.win32-py2.7.exe#md5=313b4ceed0144a3019f87a4fba5168d6 (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.7/M/MySQL-python/MySQL-python-1.2.4b1.win32-py2.7.exe#md5=e0a9f62c7a65eca79a1aa58371caa405 (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.7/M/MySQL-python/MySQL-python-1.2.4b2.win32-py2.7.exe#md5=ac5812bf27dde82c41476b09aeba3ecf (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.7/M/MySQL-python/MySQL-python-1.2.4b3.win32-py2.7.exe#md5=4596e73263008aa83d59b0541fe2ce7e (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.7/M/MySQL-python/MySQL-python-1.2.4b4.win32-py2.7.exe#md5=b53ad22d5a8e16d11ffb919eb07c9b89 (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.7/M/MySQL-python/MySQL-python-1.2.4b5.win32-py2.7.exe#md5=ad3dd07e28fd38c89a02cacb122bf27a (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.7/M/MySQL-python/MySQL-python-1.2.4c1.win32-py2.7.exe#md5=2a07d427814482fb90dbe97b591fc31d (from https://pypi.python.org/simple/MySQL-python/); unknown archive format: .exe
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.3.tar.gz#md5=215eddb6d853f6f4be5b4afc4154292f (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.3
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.3b1.tar.gz#md5=906c00cbfb81f54a474b3e7dcf7236bb (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.3b1
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.3b2.tar.gz#md5=e30ae85d490e87f3788eb4a59e590130 (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.3b2
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.3c1.tar.gz#md5=310dd856e439d070b59ece6dd7a0734d (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.3c1
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4.zip#md5=ddf2386daf10a97af115ffad2ed4a9a0 (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.4
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b1.tar.gz#md5=138669627e06f10c1c2e75122f673c21 (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.4b1
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b2.tar.gz#md5=d13f7351e195277ffd019bd7644312c9 (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.4b2
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b3.tar.gz#md5=b495d89426d83ba1e305f774e81b872f (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.4b3
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b3.zip#md5=2fb8db45f5c71dbc5869bd19eaaf546c (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.4b3
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b4.tar.gz#md5=0958cb9c23d5a656caac031c4886b1cf (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.4b4
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b4.zip#md5=2ce6fad5c5fe4074c33e8e799dc7a0af (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.4b4
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b5.tar.gz#md5=2d760ee948aff4f50d01afdf8afff48c (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.4b5
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b5.zip#md5=4f645ed23ea0f8848be77f25ffe94ade (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.4b5
    Found link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4c1.zip#md5=a05925412cd824104da064db6a889613 (from https://pypi.python.org/simple/MySQL-python/), version: 1.2.4c1
  Ignoring link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.3b1.tar.gz#md5=906c00cbfb81f54a474b3e7dcf7236bb (from https://pypi.python.org/simple/MySQL-python/), version 1.2.3b1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.3b2.tar.gz#md5=e30ae85d490e87f3788eb4a59e590130 (from https://pypi.python.org/simple/MySQL-python/), version 1.2.3b2 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.3c1.tar.gz#md5=310dd856e439d070b59ece6dd7a0734d (from https://pypi.python.org/simple/MySQL-python/), version 1.2.3c1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b1.tar.gz#md5=138669627e06f10c1c2e75122f673c21 (from https://pypi.python.org/simple/MySQL-python/), version 1.2.4b1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b2.tar.gz#md5=d13f7351e195277ffd019bd7644312c9 (from https://pypi.python.org/simple/MySQL-python/), version 1.2.4b2 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b3.tar.gz#md5=b495d89426d83ba1e305f774e81b872f (from https://pypi.python.org/simple/MySQL-python/), version 1.2.4b3 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b3.zip#md5=2fb8db45f5c71dbc5869bd19eaaf546c (from https://pypi.python.org/simple/MySQL-python/), version 1.2.4b3 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b4.tar.gz#md5=0958cb9c23d5a656caac031c4886b1cf (from https://pypi.python.org/simple/MySQL-python/), version 1.2.4b4 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b4.zip#md5=2ce6fad5c5fe4074c33e8e799dc7a0af (from https://pypi.python.org/simple/MySQL-python/), version 1.2.4b4 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b5.tar.gz#md5=2d760ee948aff4f50d01afdf8afff48c (from https://pypi.python.org/simple/MySQL-python/), version 1.2.4b5 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4b5.zip#md5=4f645ed23ea0f8848be77f25ffe94ade (from https://pypi.python.org/simple/MySQL-python/), version 1.2.4b5 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4c1.zip#md5=a05925412cd824104da064db6a889613 (from https://pypi.python.org/simple/MySQL-python/), version 1.2.4c1 is a pre-release (use --pre to allow).
  Using version 1.2.4 (newest of versions: 1.2.4, 1.2.3)
  Downloading from URL https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.4.zip#md5=ddf2386daf10a97af115ffad2ed4a9a0 (from https://pypi.python.org/simple/MySQL-python/)
  Running setup.py egg_info for package mysql-python

    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.28.tar.gz

    Extracting in /tmp/tmpzbri8D

    Now working in /tmp/tmpzbri8D/distribute-0.6.28

    Building a Distribute egg in /tmp/pip_build_root/mysql-python

    /tmp/pip_build_root/mysql-python/distribute-0.6.28-py2.7.egg

    running egg_info
    creating pip-egg-info/MySQL_python.egg-info
    writing pip-egg-info/MySQL_python.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/MySQL_python.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/MySQL_python.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/MySQL_python.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found


    reading manifest file 'pip-egg-info/MySQL_python.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/MySQL_python.egg-info/SOURCES.txt'
  Source in /tmp/pip_build_root/mysql-python has version 1.2.4, which satisfies requirement mysql-python
Installing collected packages: mysql-python

  Running setup.py install for mysql-python

    Running command /usr/bin/python -c "import setuptools;__file__='/tmp/pip_build_root/mysql-python/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kb3_p7-record/install-record.txt --single-version-externally-managed
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying _mysql_exceptions.py -> build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/__init__.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/converters.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/connections.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/cursors.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/release.py -> build/lib.linux-x86_64-2.7/MySQLdb
    copying MySQLdb/times.py -> build/lib.linux-x86_64-2.7/MySQLdb
    creating build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    running build_ext
    building '_mysql' extension

    creating build/temp.linux-x86_64-2.7
    /usr/local/i686-linux-gnu/bin/i686-linux-gnu-ccache-gcc -fno-strict-aliasing -I/usr/syno/include/ncurses/ -I. -I./Modules/expat/ -I/usr/local/i686-linux-gnu/include -DSYNO_X86 -O2 -I/usr/syno/include -g -DSYNO_PLATFORM=X64 -g -DSDK_VER_MIN_REQUIRED=400 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Dversion_info=(1,2,4,'final',1) -D__version__=1.2.4 -I/usr/local/include -I/usr/local/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o -g -DUNIV_LINUX -DUNIV_LINUX

    unable to execute /usr/local/i686-linux-gnu/bin/i686-linux-gnu-ccache-gcc: No such file or directory

    error: command '/usr/local/i686-linux-gnu/bin/i686-linux-gnu-ccache-gcc' failed with exit status 1

    Complete output from command /usr/bin/python -c "import setuptools;__file__='/tmp/pip_build_root/mysql-python/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kb3_p7-record/install-record.txt --single-version-externally-managed:

    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

copying _mysql_exceptions.py -> build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/MySQLdb

copying MySQLdb/__init__.py -> build/lib.linux-x86_64-2.7/MySQLdb

copying MySQLdb/converters.py -> build/lib.linux-x86_64-2.7/MySQLdb

copying MySQLdb/connections.py -> build/lib.linux-x86_64-2.7/MySQLdb

copying MySQLdb/cursors.py -> build/lib.linux-x86_64-2.7/MySQLdb

copying MySQLdb/release.py -> build/lib.linux-x86_64-2.7/MySQLdb

copying MySQLdb/times.py -> build/lib.linux-x86_64-2.7/MySQLdb

creating build/lib.linux-x86_64-2.7/MySQLdb/constants

copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants

running build_ext

building '_mysql' extension

creating build/temp.linux-x86_64-2.7

/usr/local/i686-linux-gnu/bin/i686-linux-gnu-ccache-gcc -fno-strict-aliasing -I/usr/syno/include/ncurses/ -I. -I./Modules/expat/ -I/usr/local/i686-linux-gnu/include -DSYNO_X86 -O2 -I/usr/syno/include -g -DSYNO_PLATFORM=X64 -g -DSDK_VER_MIN_REQUIRED=400 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Dversion_info=(1,2,4,'final',1) -D__version__=1.2.4 -I/usr/local/include -I/usr/local/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o -g -DUNIV_LINUX -DUNIV_LINUX

unable to execute /usr/local/i686-linux-gnu/bin/i686-linux-gnu-ccache-gcc: No such file or directory

error: command '/usr/local/i686-linux-gnu/bin/i686-linux-gnu-ccache-gcc' failed with exit status 1

----------------------------------------

Cleaning up...

  Removing temporary dir /tmp/pip_build_root...
Command /usr/bin/python -c "import setuptools;__file__='/tmp/pip_build_root/mysql-python/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kb3_p7-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip_build_root/mysql-python

Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 241, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/local/lib/python2.7/site-packages/pip/req.py", line 1298, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/req.py", line 625, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/local/lib/python2.7/site-packages/pip/util.py", line 670, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/python -c "import setuptools;__file__='/tmp/pip_build_root/mysql-python/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kb3_p7-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip_build_root/mysql-python

```

**Comment by Watzmann** [comment]
I found your post on http://forum.synology.com/enu/viewtopic.php?f=35&t=67923#p285373 and I agree:

Problem seems to be:

<pre>
building '_mysql' extension
creating build/temp.linux-x86_64-2.7
unable to execute /usr/local/i686-linux-gnu/bin/i686-linux-gnu-ccache-gcc: No such file or directory
</pre>

Maybe your gcc installation is not complete or incompatible. At this point I am using "x86_64-linux-gnu-gcc" instead of "i686-linux-gnu-ccache-gcc". I don't know about "i686-linux-gnu-ccache-gcc" but maybe it is a cross compiler or the likes.

Do any other python installations work, like 'pip install twisted'?

And talking about your problem with 'mysql_config' I'll advise you to do a

<pre>
sudo apt-get install libpython-dev python-dev
</pre>

instead of manually installing separate files. There may be important side effects.

Good luck

**Comment by farcepest** [comment]
It's a problem either with your compiler setup, or your Python setuptools. The real question, in response to the previous comment, is: Can you build any Python packages which have a C component? Some examples: pillow, python-ldap. I'm pretty sure you can't, which is why I've marked this "invalid".
