### ISSUE TITLE
Cannot Install Mysql

### ISSUE THREAD

**Issue by marcuxyz** [farcepest/MySQLdb1#98]
pip install mysql-python

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aOV0uI/mysql-python

**Comment by harshanarayana** [comment]
It is possible that your mysql_config is missing. If it's not installed, then use apt-get to install it on your machine before you proceed with installation of MySQL-python

`sudo apt-get install libmysqlclient-dev`

**Comment by joaopauloribeiro** [comment]
I have a similar issue when installing with pip:
Collecting MySQL-python
  Using cached MySQL-python-1.2.5.zip
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pycharm-packaging0.tmp/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/tmp/pycharm-packaging0.tmp/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ImportError: No module named 'ConfigParser'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

```
  File "<string>", line 20, in <module>

  File "/tmp/pycharm-packaging0.tmp/MySQL-python/setup.py", line 13, in <module>

    from setup_posix import get_config

  File "/tmp/pycharm-packaging0.tmp/MySQL-python/setup_posix.py", line 2, in <module>

    from ConfigParser import SafeConfigParser

ImportError: No module named 'ConfigParser'

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pycharm-packaging0.tmp/MySQL-python
```

my python is:

Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
[GCC 4.9.2 20150304 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by claudep** [comment]
mysqlclient is the de-facto successor of MySQL-python.
https://pypi.python.org/pypi/mysqlclient

**Comment by joaopauloribeiro** [comment]
Thanks!
that worked just fine!

**Comment by extremewaysback** [comment]
pip install MySQL-python got the following error on MAC:
  Downloading mysql-0.0.1.tar.gz
Collecting MySQL-python (from mysql)
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/y4/gt987g8j26z1s6kpdp7xdz2m0000gn/T/pip-build-bRu91W/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))

**Comment by yimaoFromChina** [comment]
I  meet same problem,who  can help me solve it ,thanks.
    D:\Progam\visualStudio2015\VC\BIN\amd64\link.exe /nologo /INCREMENTAL:NO /L
CG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files (x86)\M
SQL\MySQL Connector C 6.0.2\lib\opt" /LIBPATH:d:\progam\python3.5\libs /LIBPATH
d:\progam\python3.5\PCbuild\amd64 /LIBPATH:D:\Progam\visualStudio2015\VC\LIB\am
64 /LIBPATH:D:\Progam\visualStudio2015\VC\ATLMFC\LIB\amd64 "/LIBPATH:C:\Program
Files (x86)\Windows Kits\10\lib\10.0.10586.0\ucrt\x64" "/LIBPATH:C:\Program Fil
s (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86
\Windows Kits\10\lib\10.0.10586.0\um\x64" kernel32.lib advapi32.lib wsock32.lib
mysqlclient.lib /EXPORT:PyInit__mysql build\temp.win-amd64-3.5\Release\_mysql.o
j /OUT:build\lib.win-amd64-3.5\_mysql.cp35-win_amd64.pyd /IMPLIB:build\temp.win
amd64-3.5\Release\_mysql.cp35-win_amd64.lib
    _mysql.obj : warning LNK4197: 多次指定导出“PyInit__mysql”；使用第一个规范
      正在创建库 build\temp.win-amd64-3.5\Release\_mysql.cp35-win_amd64.lib 和对
象 build\temp.win-amd64-3.5\Release\_mysql.cp35-win_amd64.exp
    _mysql.obj : error LNK2001: 无法解析的外部符号 __security_check_cookie
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_field_count
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_warning_count
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_num_rows
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_shutdown
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_real_query
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_ping
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_stat
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_insert_id
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_next_result
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_ssl_set
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_get_proto_info
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_store_result
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_change_user
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_get_character_set_info
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_commit
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_get_server_info
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_data_seek
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_errno
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_real_connect
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_rollback
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_options
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_get_host_info
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_fetch_lengths
    _mysql.obj : error LNK2001: 无法解析的外部符号 __imp_strncpy
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_affected_rows
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_real_escape_string
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_debug
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_set_server_option
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_server_end
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_get_client_info
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_server_init
    _mysql.obj : error LNK2001: 无法解析的外部符号 __imp___stdio_common_vsprintf

    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_free_result
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_fetch_row
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_thread_safe
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_fetch_fields
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_character_set_name
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_info
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_escape_string
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_num_fields
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_kill
    _mysql.obj : error LNK2001: 无法解析的外部符号 __imp_strncat
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_use_result
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_select_db
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_sqlstate
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_init
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_row_seek
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_autocommit
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_error
    _mysql.obj : error LNK2001: 无法解析的外部符号 mysql_thread_id
    LINK : error LNK2001: 无法解析的外部符号 _DllMainCRTStartup
    build\lib.win-amd64-3.5\_mysql.cp35-win_amd64.pyd : fatal error LNK1120: 56
个无法解析的外部命令
    error: command 'D:\\Progam\\visualStudio2015\\VC\\BIN\\amd64\\link.exe' fail
ed with exit status 1120

    ----------------------------------------
Command "d:\progam\python3.5\python.exe -u -c "import setuptools, tokenize;__fil
e__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-build-dnc14qk4\\MySQL-python
\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\
r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:
\Users\ADMINI~1\AppData\Local\Temp\pip-jiw33j81-record\install-record.txt --sing
le-version-externally-managed --compile" failed with error code 1 in C:\Users\AD
MINI~1\AppData\Local\Temp\pip-build-dnc14qk4\MySQL-python\
